const { chromium } = require('playwright');
(async()=>{ const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--mute-audio']});
 const p=await b.newPage({viewport:{width:768,height:768}});
 for(const s of ['clock','notext','camlock']) await p.addInitScript({path:'/root/holo/'+s+'.js'});
 await p.goto('http://localhost:8765/khoa-holo.html?embed=hero&lang=en');
 await p.addStyleTag({content:'html,body,#stage{background:#000!important} body *{visibility:hidden!important} canvas{visibility:visible!important} #fx{visibility:hidden!important}'});
 await p.evaluate(()=>{ window.fbIntroQuiet=true; });
 const FPS=30, dt=1000/FPS; let f=0;
 const go=async sec=>{ while(f<sec*FPS){ await p.evaluate(d=>window.__step(d),dt); f++; } };
 const shot=async n=>p.screenshot({path:'/root/holo/st-'+n+'.png'});
 await go(1.6); await shot('asm1');
 await go(3.5); await shot('asm2');
 await go(8.0); await p.evaluate(()=>window.serraLookAt&&window.serraLookAt(-1.6,0.2));
 await go(9.5); await shot('left');
 await p.evaluate(()=>window.serraLookAt&&window.serraLookAt(1.6,-0.4));
 await go(11.0); await shot('right');
 await p.evaluate(()=>window.fbSituation('backup'));
 await go(13.0); await shot('green');
 await b.close(); console.log('ok'); })();
